#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
reload(sys)
sys.setdefaultencoding('utf8')

import rospy
import rospkg
from iot_node.service import Service
# from iot_node.controller import Controller

if __name__ == '__main__':
    # print rospkg('')
    rospy.init_node('iot_node')
    # c = Controller()
    s = Service()
    rospy.spin()
